FROM alpine AS cidata
RUN apk add xorriso
WORKDIR /usr/local/share/cidata
COPY user-data meta-data .
COPY --from=port port.diff .
RUN xorriso -volid CIDATA -joliet on -rockridge on -outdev localds.img -map . /

FROM alpine AS a
RUN apk add qemu-system-x86_64 qemu-img
VOLUME /usr/local/share/vm/
WORKDIR /usr/local/share/vm/
ARG OSREV=7.8
COPY --from=ghcr.io/3405691582/openbsd-amd64:${OSREV} /usr/local/share/openbsd/os.qcow2 os.qcow2
COPY --from=cidata /usr/local/share/cidata/localds.img localds.img
ARG CPU=16 MEM=64G KVM=-enable-kvm SCRATCH=64G TAPE=2G
RUN qemu-img create -f qcow2 scratch.qcow2 ${SCRATCH} && \
    qemu-img create -f qcow2 out.qcow2 ${TAPE} && \
    qemu-system-x86_64 \
    ${KVM} \
    -smp ${CPU} \
    -m ${MEM} \
    -nodefaults -no-user-config -nographic \
    -serial stdio \
    -nic user,model=virtio-net-pci \
    -drive id=os,file=/usr/local/share/vm/os.qcow2,format=qcow2,if=none \
    -device virtio-blk-pci,drive=os \
    -drive id=out,file=/usr/local/share/vm/out.qcow2,format=qcow2,if=none \
    -device virtio-blk-pci,drive=out \
    -drive id=scratch,file=/usr/local/share/vm/scratch.qcow2,format=qcow2,if=none \
    -device virtio-blk-pci,drive=scratch \
    -drive id=cidata,file=/usr/local/share/vm/localds.img,format=raw,if=none \
    -device virtio-blk-pci,drive=cidata && \
    qemu-img convert -f qcow2 -O raw out.qcow2 out.tar && \
    mkdir /usr/local/share/tape/ && \
    tar x -C /usr/local/share/tape/ -vf out.tar

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/3405691582/swift-bootstrap
LABEL org.opencontainers.image.description 'OpenBSD/amd64 binary packages for Swift.'
COPY --from=a /usr/local/share/tape/ /usr/local/share/swift/
